name: Deploy Website to S3 and Invalidate CloudFront Cache

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read   # Allows the workflow to access repository content

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configure AWS credentials using OIDC to assume the IAM role
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1  # Replace with your AWS region

      # Step 3: Sync website content to the S3 bucket
      - name: Sync website to S3
        run: |
          aws s3 sync ./website/dist s3://danresume --delete
        # Ensure the directory './public' matches where your website content is located
        # Replace 'YOUR-S3-BUCKET-NAME' with your actual S3 bucket name

      # Step 4: Invalidate CloudFront cache to ensure new content is served
      - name: Create CloudFront invalidation
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
