name: Website Redeploy

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions:
 id-token: write
 contents: read

jobs:
  redeploy_website:
    name: Redeploy Website
    runs-on: ubuntu-latest

    steps:
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN_SECRET }}
        role-session-name: github_actions_terraform_cred
        aws-region: us-east-1

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Uploads to S3
      run: |
        aws s3 sync ./website s3://${{ secrets.AWS_BUCKET_SECRET }}

    - name: Invalidate Cloudfront Distribution
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION_SECRET }}
        PATHS: "/*"
        AWS_REGION: "us-east-1"
    
    - name: run cypress tests with firefox
      uses: cypress-io/github-action@v4
      with:
        browser: firefox
